#!/bin/bash
printf "\n:: Running build for Audio Cache Test..."
# See https://developers.google.com/web/tools/workbox/guides/precache-files/cli
#workbox wizard --injectManifest
printf "\n\n:: 1. Injecting Workbox pre-cache:\n\n"
workbox injectManifest workbox-src/workbox-config.js
if [ "$1" == "deploy" ]; then
  printf "\n\n:: 2. Syncing www to firebase-deploy directory:\n\n"
  rsync -v -a www/ firebase-deploy/
  printf "\n\n:: 3. Deploying app to firebase:\n"
  if [ "$2" == "debug" ]; then
    firebase --debug --only hosting deploy
  else
    firebase deploy
  fi
fi